__exc__ = Exception("`subprocess` module is unavailable in Pyto! Use `os.system` instead.")

def call(args, *, stdin=None, stdout=None, stderr=None, shell=False, timeout=None):
    raise __exc__

def check_call(args, *, stdin=None, stdout=None, stderr=None, shell=False, timeout=None):
    raise __exc__

def check_output(args, *, input=None, stdin=None, stderr=None, shell=False, universal_newlines=False, timeout=None):
    raise __exc__

